### ISSUE TITLE
HTTP error querying regression regions

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSSServices#255]
At some points when we do a post request to https://streamstats.usgs.gov/nssservices/regressionregions/bylocation
 we are seeing the following error:

`{"error":["Error occured computing percent overlay XX000: Error performing intersection: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -1447872.8043000014 1107203.4697999926 at -1447872.8043000014 1107203.4697999926","XX000: Error performing intersection: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -1447872.8043000014 1107203.4697999926 at -1447872.8043000014 1107203.4697999926"]}`

testing points:
46.63709, -112.08449 (MT)
37.079148, -81.745087
36.58327919861727, -81.086783 (VA)
41.51897292296264, -71.44550800323486

**Comment by amedenblik** [comment]
We think this issue was caused by problematic data in the Locations table in the NSS database. We have reverted the Production database, so https://streamstats.usgs.gov/nssservices/regressionregions/bylocation (on Production) now works. We still need to fix the Locations table in the Test database.

**Comment by amedenblik** [comment]
Yesterday, the Locations table in the Test database was reverted to the status of Production on March 22, meaning all changes to the table since February migration were lost. We are now waiting for Ryan to re-copy the following RegressionRegion polygons: 

GC774 EC_Plains_Region_Active_Channel
GC1658 IL_Flow_duration_Reg_1_DA_only_2014_5177
GC1660 IL_Flow_duration_Reg_2_DA_only_2014_5177
GC1663 IN_Flow_duration_Reg_1_DA_only_2014_5177
GC1663 IN_Flow_duration_Reg_1_DA_only_2014_5177
GC1664 IN_Flow_duration_Reg_1_Multivar_2014_5177
GC1664 IN_Flow_duration_Reg_1_Multivar_2014_5177
GC1665 IN_Flow_duration_Reg_2_DA_only_2014_5177
GC1666 IN_Flow_duration_Reg_3_DA_only_2014_5177
GC1667 IN_Flow_duration_Reg_3_Multivar_2014_5177
GC1675 W_Region_BasinC_2015_5019F
GC1677 NW_Foothills_Region_BasinC_2015_5019F
GC1678 NE_Plains_Region_BasinC_2015_5019F
GC1679 EC_Plains_Region_BasinC_2015_5019F
GC1680 SE_Plains_Region_BasinC_2015_5019F
GC1682 SW_Region_BasinC_2015_5019F
GC1688 UpYellow_CentMt_Region_Annual_MeanDur_2015_5019G
GC1768 NW_Region_BasinC_2015_5019F
GC1829 EC_Plains_Region_Active_Channel_SIR_2020_5142
GC1830 EC_Plains_Region_Bankfull_SIR_2020_5142
GC1831 EC_Plains_Region_Aerial_Photo_SIR_2020_5142
GC1832 NE_Plains_Region_Active_Channel_SIR_2020_5142
GC1833 NE_Plains_Region_Bankfull_SIR_2020_5142
GC1834 NE_Plains_Region_Aerial_Photo_SIR_2020_5142
GC1835 NW_Foothills_Region_Active_Channel_SIR_2020_5142
GC1836 NW_Foothills_Region_Bankfull_SIR_2020_5142
GC1837 NW_Foothills_Region_Aerial_Photo_SIR_2020_5142
GC1838 NW_Region_Active_Channel_SIR_2020_5142
GC1839 NW_Region_Bankfull_SIR_2020_5142
GC1840 NW_Region_Aerial_Photo_SIR_2020_5142
GC1841 SE_Plains_Region_Active_Channel_SIR_2020_5142
GC1842 SE_Plains_Region_Bankfull_SIR_2020_5142
GC1843 SE_Plains_Region_Aerial_Photo_SIR_2020_5142
GC1844 SW_Region_Active_Channel_SIR_2020_5142
GC1845 SW_Region_Bankfull_SIR_2020_5142
GC1846 SW_Region_Aerial_Photo_SIR_2020_5142
GC1847 UpYllw_CentMount_Region_Act_Channel_SIR_2020_5142
GC1848 UpYllw_CentMount_Region_Bankfull_SIR_2020_5142
GC1849 UpYllw_CentMount_Region_Aerial_Photo_SIR_2020_5142
GC1850 W_Region_Active_Channel_SIR_2020_5142
GC1851 W_Region_Bankfull_SIR_2020_5142
GC1852 W_Region_Aerial_Photo_SIR_2020_5142
GC1883 DE_LowFlow_Coastal_Plain_2022_5005
GC1884 DE_LowFlow_Piedmont_2022_5005
GC1885 Low_Flow_LA_Region_1_TR75
GC1886 Low_Flow_LA_Region_2_TR75
GC1887 Low_Flow_LA_Region_3_TR75
GC1891 IN_Flow_duration_Reg_2_Multivar_2014_5177
GC1894 Crippen_Bue_Region_1
GC1895 Crippen_Bue_Region_2
GC1896 Crippen_Bue_Region_3
GC1897 Crippen_Bue_Region_4
GC1898 Crippen_Bue_Region_5
GC1899 Crippen_Bue_Region_6
GC1900 Crippen_Bue_Region_7
GC1901 Crippen_Bue_Region_8
GC1902 Crippen_Bue_Region_9
GC1903 Crippen_Bue_Region_10
GC1904 Crippen_Bue_Region_11
GC1905 Crippen_Bue_Region_12
GC1906 Crippen_Bue_Region_13
GC1907 Crippen_Bue_Region_14
GC1908 Crippen_Bue_Region_15
GC1909 Crippen_Bue_Region_16
GC1910 Crippen_Bue_Region_17
GC1911 Maine_August_Unit_Baseflow_RivResAppl_2021
GC1912 Peakflow_MS_AlvlPln_SIR_2021_5046
GC1912 Peakflow_MS_AlvlPln_SIR_2021_5046

**Comment by amedenblik** [comment]
Ryan has updated the Locations table and we are still having issues.

46.63709, -112.08449 (MT): Test ❌, Prod ✅
37.079148, -81.745087 (VA): Test ❌, Prod ❌
36.58327919861727, -81.086783 (VA): Test ❌, Prod ❌
41.51897292296264, -71.44550800323486 (RI): Test ❌, Prod ❌

**Comment by harper-wavra** [comment]
Ryan updated the polygons on test, and we pushed locations table to prod.

46.63709, -112.08449 (MT): Test ✅
37.079148, -81.745087 (VA): Test ✅
36.58327919861727, -81.086783 (VA): Test ✅
41.51897292296264, -71.44550800323486 (RI): Test ✅
33.788175, -84.519971 (GA): Test ✅
41.99368, -73.51263 (NY and CT): Test ✅
33.8844, -84.1330 (Ga): Test ✅

**Comment by harper-wavra** [comment]
Closing issue for now (we might still see issues in CT), will reopen if we get more tickets.
