### ISSUE TITLE
issues with nssservicesv2

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSSServices#84]
I think some of these were fixed before, it's possible edits were overwritten or an old build was posted?

- [x] when posting regression region - getting `no region exists with identifier` error on all regions

- [x] put/deletes are no longer working (getting that `405 - HTTP verb not allowed` error again)

- [x] Id not creating uniquely on most, I created a workaround in the code for now

- [x] regression regions - (before reg region post stopped working) reg regions adding to whole list but not to region's reg regions

- [x] regression types - adding to whole list but not to region's reg types

- [x] stat groups - after post can search using `statisticgroups/{ID}`, ~not showing up in `/statisticgroups` list~, not showing up in regions if posted that way

- [x] scenarios are missing the links/citations property - do we pull that based on the regression regions now?

**Comment by kjacobsen16** [comment]
example request for Statistic Groups:
https://test.streamstats.usgs.gov/nssservicesv2/statisticgroups
```
{
    "id": 36,
    "name": "Test Statistic Groups",
    "code": "TSG"
  }
```

Returns the body, but now can't find it at `/statisticgroups` or `/statisticgroups/36`

Also, I can't post without giving the ID.

**Comment by kjacobsen16** [comment]
example for Regression regions:
https://test.streamstats.usgs.gov/nssservicesv2/regions/75/regressionregions
request body:
```
{
    "name": "Test_regreg",
    "code": "TREGREG",
    "description": ""
  }
```
Response body:
```
{
  "id": 775,
  "name": "Test_regreg",
  "code": "TREGREG",
  "description": "",
  "statusID": 1,
  "regionRegressionRegions": [
    {
      "regionID": 75,
      "regressionRegionID": 775
    }
  ]
}
```

but empty array at `/regions/75/regressionregions`. In this case, I can see it at `/regressionregions`

**Comment by jknewson** [comment]
I need more information on 'Id not creating uniquely on most,' If its what I think it is, This is by design. I've designed the post to search for duplicates before adding to the db. If for example there is already a regressionregion with the same name and code then it will be selected instead of added, returning the same id. The DB prevents duplicative ID's via a constraint.

**Comment by kjacobsen16** [comment]
If I try to post a new element, like for example this unit:
```
{
    "name": "testing0410",
    "abbreviation": "T0410",
    "unitSystemTypeID": 2
  }
```

I get an error that `one of the properties is marked as a Unique index`, although there's nothing with that name or abbreviation.

Before I was able to get around this by getting the max id of all the existing units and sending an ID in the body that was one higher, but now I'm getting that error when I give an ID as well.

This is happening to me with several of the categories.

**Comment by jknewson** [comment]
ok, yes that is an error, The client code shouldn't need to worry about managing the business logic (ie what the id is/or will be), I'm working on that now, It looks as if I started this, but it looks like I forgot the lookup-type lists. Which is why its throwing an error when not passing in the ID. Its a simple fix so shouldn't take long... in the meantime, you should remove the max id method from your script (or any other db type business logic. That way if/when we (or someone else) builds a different client for these services, we have isolated all the loose ends in the services.

**Comment by kjacobsen16** [comment]
Just removed them!
